[package]
name = "cyoa-presentation"
description = "Terminal interfaces for CYOA"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cyoa-application.workspace = true
cyoa-core.workspace = true
thiserror.workspace = true
clap.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { version = "1", features = ["event", "fs"] }
signal-hook = "0.3"

[lints]
workspace = true
