[package]
name = "cyoa-infrastructure"
description = "External adapters for CYOA"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cyoa-application.workspace = true
cyoa-core.workspace = true
minijinja = "2.24.0"
schemars = "1.2.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
toml = "1.1.6"

[lints]
workspace = true
